### ISSUE TITLE
协商关于 ww-ui package 的问题

### ISSUE THREAD

**Issue by meterscao** [namewangwei/ww-ui#1]
wangwei，你好：

打扰了，我是一名来自成都的前端开发，有个事情想跟你协商下。

我们团队最近在准备部署一个自用业务的小程序UI库，一开始取名为 `wwui`，提前特地搜索了 npm 库没有占用的名字，于是按照这个部署了文档，设计了 Logo，并且申请了小程序的名字。

但是在 `npm publish` 的时候提示这个名字跟现有的 package 名字很相近，我最后搜索才发现有一个叫做 `ww-ui` 的 package。

按照路径点过来看到了你先前发布的 `ww-ui`，但是看下载提示近期没有安装量。所以想跟你协商下，不知道你的 `ww-ui` 是否可以把这个命名空间释放给我们呢，非常感谢，也期待你的回复

meters

**Comment by namewangwei** [comment]
现在还需要吗

**Comment by meterscao** [comment]
嗯，太好了，一致期待你的回复。

**Comment by meterscao** [comment]
方便的话，邮件我可以吗。xiaofeng@besttime.us
微信: meters
